config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "students#job_board"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  scope "/admin" do
    resources :languages
    resources :certifications
    resources :category_tech_skills
    resources :tech_skills
    
    resources :users
    resources :students
    resources :companies
  end

  scope "/company" do
    resources :job_campaigns do
      member do
        get 'match_students'
        put 'reject_student/:student_id', to: 'job_campaigns#reject_student', as: :reject_student
      end
    end
    get ':id/edit_profile', to: 'companies#edit', as: 'company_edit_profile'
    get ':id/profile', to: 'companies#view_profile', as: 'company_profile'
  end
  # put 'reject_student/:id', to: 'job_campaigns_students#reject_student'

  scope "/student" do
    get ':id/my_cv', to: 'students#edit', as: 'student_cv'
    get ':id/preview_cv', to: 'students#preview_cv', as: 'preview_cv'
    get 'job_board', to: 'students#job_board', as: 'student_job_board'
    get 'matched_jobs', to: 'job_campaigns#match_job_campaigns', as: 'match_job_campaigns'
  end
  
  get 'admin/job_campaigns', to: 'job_campaigns#admin_manage', as: 'admin_manage_job_campaigns'
  get 'job_campaigns/:id/preview', to: 'job_campaigns#preview_campaign', as: 'preview_campaign'
end

app/models/job_campaign.rb
class JobCampaign < ApplicationRecord
  enum skill_level: [ :internship, :freshman, :professional, :expert ]
  enum is_open: [ :yes, :no ]

  belongs_to :company

  has_many :languages_campaigns, dependent: :destroy
  has_many :languages, through: :languages_campaigns

  has_many :certifications_campaigns, dependent: :destroy
  has_many :certifications, through: :certifications_campaigns

  has_many :tech_skills_campaigns, dependent: :destroy
  has_many :tech_skills, through: :tech_skills_campaigns
  accepts_nested_attributes_for :tech_skills_campaigns, allow_destroy: true

  has_many :job_campaigns_students
  has_many :students, through: :job_campaigns_students

  validates :title, presence: true
  validates :salary, presence: true
  validates :work_hour_per_week, presence: true
  validates :gpa, presence: true
end

app/controllers/job_campaigns_controller.rb
class JobCampaignsController < ApplicationController
  before_action :find_job_campaign, only: [:preview_campaign, :match_students, :reject_student, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :edit, :destroy]

  def admin_manage
    @job_campaigns = JobCampaign.all.includes(:company)
    MatchingService.new.match_operation
  end

  def preview_campaign
    @languages = []

    @job_campaign.languages.each do |lang|
      @languages << lang.name
    end

    @certifications = @job_campaign.certifications_campaigns
    @tech_skills = @job_campaign.tech_skills_campaigns
  end

  def match_students
    students = []
    # MatchingService.new.match_operation
    JobCampaignsStudent.includes(:student).where(job_campaign_id: @job_campaign).matched.each { |jc| students << jc.student_id }
    @students = Student.includes(:user).limit(50).where(id: students).order("RAND()")
  end

  def match_job_campaigns
    job_campaigns = []
    # MatchingService.new.match_operation
    JobCampaignsStudent.includes(:job_campaign).where(student_id: current_user.student.id).each { |jc| job_campaigns << jc.job_campaign_id }
    @job_campaigns = JobCampaign.where(id: job_campaigns)
    # byebug
  end

  def reject_student
    JobCampaignsStudent.find_by(job_campaign_id: @job_campaign, student_id: params[:student_id]).rejected!
    redirect_to match_students_job_campaign_path(@job_campaign)
  end

  def index
    @job_campaigns = current_user.company.job_campaigns
  end

  def show
  end

  def new
    @job_campaign = current_user.company.job_campaigns.build
    @tech_skills = TechSkill.all
  end

  def edit
    @tech_skills = TechSkill.all
  end

  def create
    @job_campaign = current_user.company.job_campaigns.build(job_campaign_params)

    if @job_campaign.save
      redirect_to job_campaigns_path
    else
      render :new
    end
  end

  def update
    if @job_campaign.update(job_campaign_params)
      redirect_to job_campaigns_path
    else
      @tech_skills = TechSkill.all
      render :edit, collection: @tech_skills
    end
  end

  def destroy
    @job_campaign.destroy
    if current_user.admin?
      redirect_to admin_manage_job_campaigns_path
    else
      redirect_to job_campaigns_path
    end
  end

  private

  def find_job_campaign
    @job_campaign = JobCampaign.find(params[:id])
  end

  def job_campaign_params
    params.require(:job_campaign).permit(:title,
                                        :salary,
                                        :work_hour_per_week,
                                        :gpa,
                                        :is_open,
                                        :location,
                                        :quantity,
                                        :description,
                                        :min_intern_month,
                                        :skill_level,
                                        :company_id,
                                        { :language_ids => [] },
                                        { :certification_ids => [] },
                                        { :tech_skill_ids => [] },
                                        tech_skills_campaigns_attributes: [ :id, :tech_skill_id, :priority, :level, :_destroy ]
    )
  end
end

app/helpers/job_campaigns_helper.rb
module JobCampaignsHelper
end

app/views/job_campaigns/_tech_skills_campaign_fields.html.erb
<div class="nested-fields">
  <div class="row mt-2">
    <div class="col-sm-4">
      <%= f.association :tech_skill,
                        collection: @tech_skills,
                        label: false,
                        wrapper: false %>
    </div>

    <div class="col-sm-3">
      <%= f.input :priority,
                  collection: [
                                ['Required', 'required'],
                                ['Must have', 'must'],
                                ['Important', 'important']
                  ],
                  hint: 'From required to important',
                  label: false %>
    </div>

    <div class="col-sm-3">
      <%= f.input :level,
                  collection: [
                                ['Beginner', 'beginner'],
                                ['Intermediate', 'intermediate'],
                                ['Professional', 'professional']
                  ],
                  hint: 'From beginner to professional',
                  label: false %>
    </div>

    <div class="col-sm-2">
      <%= link_to_remove_association 'Remove', f, class: 'btn btn-danger float-right' %>
    </div>
  </div>
</div>

app/views/job_campaigns/admin_manage.html.erb
<div class="container" id="admin-manage-campaigns">
  <div class="row d-flex justify-content-center text-center">
    <h1>ALL CAMPAIGNS</h1>
  </div>
  <div class="row search">
      <div class="col-2"></div>
      <div class="col-8">
          <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="Search">
              <div class="input-group-append">
                <button class="btn btn-success" type="submit">Go</button>
              </div>
          </div>
      </div>
      <div class="col-2"></div>
  </div>
  
  <div class="row table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Camp #</th>
          <th>Title</th>
          <th>Company</th>
          <th>Location</th>
          <th>Action</th>
        </tr>
      </thead>
      <% @job_campaigns.each do |jc| %>
      <tbody>
        <tr>
          <td><%= jc.id %></td>
          <td><%= jc.title %></td>
          <td><%= jc.company.name %></td>
          <td><%= jc.location %></td>
          <td>
            <%= link_to "Delete", job_campaign_path(jc), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </td>
        </tr>         
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/job_campaigns/edit.html.erb
<%= simple_form_for @job_campaign, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="container" id="company-new-campaign">
  <div class="row title d-flex justify-content-center text-center">
    <h2>Edit Your Campaign</h2>
  </div>

  <div class="row" style="margin-top: 25px;">
    <div class="col-sm-2 d-flex">
      <p>Title:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :title,
                  required: true,
                  autofocus: true,
                  placeholder: "Enter campaign title",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Salary:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :salary,
                  required: false,
                  placeholder: "Enter salary (milions)",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Work Hours:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :work_hour_per_week,
                  collection: 1..40,
                  hint: "Working hours per week",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>GPA:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :gpa,
                  as: :decimal,
                  required: false,
                  placeholder: "From 0 to 10",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Location:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :location,
                  collection: ['An Giang',
                              'Bà Rịa - Vũng Tàu',
                              'Đà Nẵng',
                              'Hải Phòng',
                              'TP HCM'],
                  hint: "Working place",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Description:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :description,
                  as: :text,
                  required: false,
                  placeholder: "Say something about this campaign",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Quantity:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :quantity,
                  required: true,
                  placeholder: "Enter recruitment quantity",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Minimum Month:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :min_intern_month,
                  required: true,
                  placeholder: "Enter minimum month for working period",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Skill Level:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :skill_level,
                  collection: [
                                ['Internship', 'internship'],
                                ['Freshman', 'freshman'],
                                ['Professional', 'professional'],
                                ['Expert', 'expert']
                              ],
                  hint: "Level requirement",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Is Open?:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :is_open,
                  collection: [
                                ['Yes', 'yes'],
                                ['No', 'no']
                              ],
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Certifications:</p>
    </div>
    <div class="col-sm-4">
      <%= f.association :certifications,
                        input_html: { multiple: true },
                        hint: 'Hold Ctrl and choose certifications your company requires',
                        label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Languages:</p>
    </div>
    <div class="col-sm-4">
      <%= f.association :languages,
                        input_html: { multiple: true },
                        hint: 'Hold Ctrl and choose languages your company requires',
                        label: false %>
    </div>
  </div>

  <div class="row" style="margin-top:10px">
    <div class="col-sm-2 d-flex">
      <p>Skills:</p>
    </div>
    <div class="col-sm-10">
      <div class="row d-flex text-center" style="font-size:20px; font-weight: 600;">
        <div class="col-sm-4">Skill Name</div>
        <div class="col-sm-3">Priority</div>
        <div class="col-sm-3 pl-2">Level</div>
        <div class="col-sm-2 new-tech-skills">
          <%= link_to_add_association 'Add Skill', f, :tech_skills_campaigns,
                                                data: { association_insertion_node: ".tech_skills_place",
                                                        association_insertion_method: :append },
                                                class: 'btn btn-info float-right' %>
        </div>
      </div>
    </div>
  </div>

  <div class="row" style="margin-top:5px">
    <div class="col-sm-2 d-flex">
        <p></p>
    </div>
    <div class="col-sm-10">
      <div class="row">
        <div class="col-sm tech_skills_place">
          <%= f.simple_fields_for :tech_skills_campaigns do |tech_camp| %>
            <%= render "tech_skills_campaign_fields", f: tech_camp, collection: @tech_skills %>
          <% end %>
        </div>
      </div>  
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
      <%= f.button :submit, "Save", class: "btn btn-success w-100" %>
    </div>
  </div>
</div>
<% end %>

app/views/job_campaigns/index.html.erb
<div class="container" id="company-all-campaigns">
  <div class="row d-flex justify-content-center text-center" style="padding-top: 30px;"><h1>Your Campaign</h1></div>
  <div class="row d-flex control_button">
    <div class="col d-flex justify-content-center"> 
      <%= link_to "Add Campaign", new_job_campaign_path, class: "btn btn-secondary" %>
    </div>

  </div>
  <div class="row" style = "padding-top:30px">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Camp #</th>
          <th>Title</th>
          <th>Salary</th>
          <th>Work Hours</th>
          <th>Location</th>
          <th>Open</th>
          <th>Preview</th>
          <th>Edit</th>
          <th>Students</th>
          <th>Close Campaign</th>
        </tr>
      </thead>
      <% @job_campaigns.each do |jc| %>
      <tbody>
        <tr>
          <td><%= jc.id %></td>
          <td class="text-truncate" style="max-width: 250px"><%= jc.title %></td>
          <td><%= jc.salary %></td>
          <td><%= jc.work_hour_per_week %></td>
          <td><%= jc.location %></td>
          <td class="text-capitalize"><%= jc.is_open %></td>
          <td>
            <%= link_to "Preview", preview_campaign_path(jc), class: "btn btn-primary mr-1" %>
          </td>
          <td>
            <%= link_to "Edit", edit_job_campaign_path(jc), class: "btn btn-primary mr-1" %>
          </td>
          <td>
            <%= link_to "View", match_students_job_campaign_path(jc), class: "btn btn-primary mr-1" %>
          </td>
          <td><a href="#">Close</a></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/job_campaigns/match_job_campaigns.html.erb
<div class="container" id="company-match-students">
  <div class="row d-flex justify-content-center text-center" style="padding-top: 30px;">
    <h1><strong>Jobs match you</strong></h1>
  </div>
  <div class="row d-flex justify-content-center text-center py-3">
    <h2>These are jobs that suit you CV the most</h2>
  </div>
  <div class="row">
    <% @job_campaigns.each do |jc| %>
    <div class="col-sm-4">
      <div class="profile_container" id="logo-box">
        <div class="avatar_container d-flex justify-content-center">
          <% if jc.company.logo.attached? %>
            <%= image_tag jc.company.logo.variant(resize_to_fill: [250, 250]) %>
          <% else %>
            <%= image_tag "default-company-logo.png", style:"width:250px" %>
          <% end %>
        </div>
        <div class="text-center text-truncate font-weight-bold px-3 py-2" style="max-width: 100%">
          <%= jc.title %>
        </div>
        <div>
          <%= link_to "View", preview_campaign_path(jc), class: "btn view_btn" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/job_campaigns/match_students.html.erb
<div class="container" id="company-match-students">
  <div class="row d-flex justify-content-center text-center" style="padding-top: 30px;">
    <h1><strong>Students that match your Campaign</strong></h1>
  </div>
  <div class="row d-flex justify-content-center text-center py-3">
    <h2><strong><%= @job_campaign.title %></strong></h2>
  </div>
  <div class="row">
    <% @students.includes(avatar_attachment: :blob).each do |stud| %>
    <div class="col-sm-4 my-2">
      <div class="profile_container">
        <div class="avatar_container d-flex justify-content-center">
          <% if stud.avatar.attached? %>
            <%= image_tag stud.avatar.variant(resize_to_fill: [350, 250]) %>
          <% else %>
            <%= image_tag "default-student-avatar.png", style:"width:250px" %>
          <% end %>
        </div>
        <div class="name d-flex justify-content-center text-center my-2 font-weight-bold">
          <% if stud.name? %>
            <%= link_to preview_cv_path(stud.user) do %>
              <%= stud.name %>
            <% end %>
          <% else %>
            Null
          <% end %>
        </div>
        <%= link_to 'Reject', reject_student_job_campaign_path(@job_campaign, stud.id), method: :put, class: "btn btn-secondary w-100 reject-btn" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/job_campaigns/new.html.erb
<%= simple_form_for @job_campaign, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="container" id="company-new-campaign">
  <div class="row title d-flex justify-content-center text-center">
    <h2>Add Your Campaign</h2>
  </div>

  <div class="row" style="margin-top: 25px;">
    <div class="col-sm-2 d-flex">
      <p>Title:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :title,
                  required: true,
                  autofocus: true,
                  placeholder: "Enter campaign title",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Salary:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :salary,
                  required: false,
                  placeholder: "Enter salary (milions)",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Work Hours:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :work_hour_per_week,
                  collection: 1..40,
                  hint: "Working hours per week",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>GPA:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :gpa,
                  as: :decimal,
                  required: false,
                  placeholder: "From 0 to 10",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Location:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :location,
                  collection: ['An Giang',
                              'Bà Rịa - Vũng Tàu',
                              'Đà Nẵng',
                              'Hải Phòng',
                              'TP HCM'],
                  hint: "Working place",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Description:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :description,
                  as: :text,
                  required: false,
                  placeholder: "Say something about this campaign",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Quantity:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :quantity,
                  required: true,
                  placeholder: "Enter recruitment quantity",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Minimum Month:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :min_intern_month,
                  required: true,
                  placeholder: "Enter minimum month for working period",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Skill Level:</p>
    </div>
    <div class="col-sm-10">
      <%= f.input :skill_level,
                  collection: [
                                ['Internship', 'internship'],
                                ['Freshman', 'freshman'],
                                ['Professional', 'professional'],
                                ['Expert', 'expert']
                              ],
                  hint: "Level requirement",
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Certifications:</p>
    </div>
    <div class="col-sm-4">
      <%= f.association :certifications,
                  input_html: { multiple: true },
                  hint: 'Hold Ctrl and choose certifications your company requires',
                  label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 d-flex">
      <p>Languages:</p>
    </div>
    <div class="col-sm-4">
      <%= f.association :languages,
                  input_html: { multiple: true },
                  hint: 'Hold Ctrl and choose languages your company requires',
                  label: false %>
    </div>
  </div>

  <div class="row" style="margin-top:10px">
    <div class="col-sm-2 d-flex">
      <p>Skills:</p>
    </div>
    <div class="col-sm-10">
      <div class="row d-flex text-center" style="font-size:20px; font-weight: 600;">
        <div class="col-sm-4">Skill Name</div>
        <div class="col-sm-3">Priority</div>
        <div class="col-sm-3 pl-2">Level</div>
        <div class="col-sm-2 new-tech-skills">
          <%= link_to_add_association 'Add Skill', f, :tech_skills_campaigns,
                                                data: { association_insertion_node: ".tech_skills_place",
                                                        association_insertion_method: :append },
                                                class: 'btn btn-info float-right' %>
        </div>
      </div>
    </div>
  </div>

  <div class="row" style="margin-top:5px">
    <div class="col-sm-2 d-flex">
        <p></p>
    </div>
    <div class="col-sm-10">
      <div class="row">
        <div class="col-sm tech_skills_place">
          <%= f.simple_fields_for :tech_skills_campaigns do |tech_camp| %>
            <%= render "tech_skills_campaign_fields", f: tech_camp, collection: @tech_skills %>
          <% end %>
        </div>
      </div>  
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
      <%= f.button :submit, "Publish Campaign", class: "btn btn-success w-100" %>
    </div>
  </div>
</div>
<% end %>

app/views/job_campaigns/preview_campaign.html.erb
<div class="container mt-4" id="company-preview-campaign">
  <div class="row d-flex justify-content-center text-center">
    <h2>
      <strong><%= @job_campaign.title %></strong>
    </h2>
  </div>
  <div class="row d-flex justify-content-center text-center">
      <h3>
        <%= link_to company_profile_path(@job_campaign.company), class: "text-decoration-none" do %>  
          <%= @job_campaign.company.name %>
        <% end %>
      </h3>
  </div>
  <div class="row d-flex justify-content-center">
      <div class="avatar">
        <% if @job_campaign.company.logo.attached? %>
          <%= image_tag @job_campaign.company.logo.variant(resize_to_fill: [200, 200]) %>
        <% else %>
          <%= image_tag "default-company-logo.png", style:"width:200px" %>
        <% end %>
      </div>
  </div>
  <div class="row slash d-flex justify-content-center text-center">
      <h2>Job Basic Info</h2>
  </div>

  <div class="row">
    <div class="col-sm-2">
      <p>Salary:</p>
    </div>
    <div class="col-sm-10 font-weight-bold">
      <%= @job_campaign.salary %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <p>Work Hours:</p>
    </div>
    <div class="col-sm-10 font-weight-bold">
      <%= @job_campaign.work_hour_per_week %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <p>Required GPA:</p>
    </div>
    <div class="col-sm-10 font-weight-bold">
      >= <%= @job_campaign.gpa %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <p>Location:</p>
    </div>
    <div class="col-sm-10 font-weight-bold">
      <%= @job_campaign.location %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <p>Quantity:</p>
    </div>
    <div class="col-sm-10 font-weight-bold">
      <%= @job_campaign.quantity %> people
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <p>Language:</p>
    </div>
    <div class="col-sm-10 font-weight-bold">
      <%= @languages.join(", ") %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <p>Description:</p>
    </div>
    <div class="col-sm-10 font-weight-bold">
      <p>
        <%= @job_campaign.description %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <p>Skill Level:</p>
    </div>
    <div class="col-sm-10 font-weight-bold text-capitalize">
      <%= @job_campaign.skill_level %>
    </div>
  </div>
  <div class="row slash d-flex justify-content-center text-center">
      <h2>Certification Required</h2>
  </div>
  <div class="row">
    <div class="col-sm-2">
        <p>Certifications:</p>
    </div>
    <div class="col-sm-10">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Cert</th>
            <th>Vendor</th>
          </tr>
        </thead>
        <% @certifications.each do |cert| %>
        <tbody>
          <tr>
            <td><%= cert.certification.name %></td>
            <td><%= cert.certification.vendor %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row slash d-flex justify-content-center text-center">
      <h2>Skill Required</h2>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <p>Technical Skills:</p>
    </div>
    <div class="col-sm-10">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Skill</th>
            <th>Priority</th>
            <th>Level</th>
          </tr>
        </thead>
        <% @tech_skills.each do |tech| %>
        <tbody>
          <tr>
            <td><%= tech.tech_skill.name %></td>
            <td class="text-capitalize"><%= tech.priority %></td>
            <td class="text-capitalize"><%= tech.level %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>