config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "students#job_board"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  scope "/admin" do
    resources :languages
    resources :certifications
    resources :category_tech_skills
    resources :tech_skills
    
    resources :users
    resources :students
    resources :companies
  end

  scope "/company" do
    resources :job_campaigns do
      member do
        get 'match_students'
        put 'reject_student/:student_id', to: 'job_campaigns#reject_student', as: :reject_student
      end
    end
    get ':id/edit_profile', to: 'companies#edit', as: 'company_edit_profile'
    get ':id/profile', to: 'companies#view_profile', as: 'company_profile'
  end
  # put 'reject_student/:id', to: 'job_campaigns_students#reject_student'

  scope "/student" do
    get ':id/my_cv', to: 'students#edit', as: 'student_cv'
    get ':id/preview_cv', to: 'students#preview_cv', as: 'preview_cv'
    get 'job_board', to: 'students#job_board', as: 'student_job_board'
    get 'matched_jobs', to: 'job_campaigns#match_job_campaigns', as: 'match_job_campaigns'
  end
  
  get 'admin/job_campaigns', to: 'job_campaigns#admin_manage', as: 'admin_manage_job_campaigns'
  get 'job_campaigns/:id/preview', to: 'job_campaigns#preview_campaign', as: 'preview_campaign'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_tech_skill.rb
class CategoryTechSkill < ApplicationRecord
  has_many :tech_skills
end

app/models/certification.rb
class Certification < ApplicationRecord
  has_many :certifications_users
  has_many :users, through: :certifications_users

  has_many :certifications_campaigns
  has_many :job_campaigns, through: :certifications_campaigns
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_one_attached :logo
  has_one_attached :headline

  has_many :job_campaigns
end

app/models/job_campaign.rb
class JobCampaign < ApplicationRecord
  enum skill_level: [ :internship, :freshman, :professional, :expert ]
  enum is_open: [ :yes, :no ]

  belongs_to :company

  has_many :languages_campaigns, dependent: :destroy
  has_many :languages, through: :languages_campaigns

  has_many :certifications_campaigns, dependent: :destroy
  has_many :certifications, through: :certifications_campaigns

  has_many :tech_skills_campaigns, dependent: :destroy
  has_many :tech_skills, through: :tech_skills_campaigns
  accepts_nested_attributes_for :tech_skills_campaigns, allow_destroy: true

  has_many :job_campaigns_students
  has_many :students, through: :job_campaigns_students

  validates :title, presence: true
  validates :salary, presence: true
  validates :work_hour_per_week, presence: true
  validates :gpa, presence: true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :languages_users
  has_many :users, through: :languages_users

  has_many :languages_campaigns
  has_many :job_campaigns, through: :languages_campaigns
end

app/models/languages_campaign.rb
class LanguagesCampaign < ApplicationRecord
  belongs_to :language
  belongs_to :job_campaign
end

app/models/languages_student.rb
class LanguagesStudent < ApplicationRecord
  belongs_to :language
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  enum is_open: [ :yes, :no ]

  belongs_to :user

  has_one_attached :avatar

  has_many :certifications_students
  has_many :certifications, through: :certifications_students

  has_many :languages_students
  has_many :languages, through: :languages_students

  has_many :tech_skills_students
  has_many :tech_skills, through: :tech_skills_students
  accepts_nested_attributes_for :tech_skills_students, allow_destroy: true

  has_many :job_campaigns_students
  has_many :job_campaigns, through: :job_campaigns_students
end

app/models/tech_skill.rb
class TechSkill < ApplicationRecord
  belongs_to :category_tech_skill, optional: true

  has_many :tech_skills_users
  has_many :users, through: :tech_skills_users

  has_many :tech_skills_campaigns
  has_many :tech_skills, through: :tech_skills_campaigns

  validates :name, presence: true
end

app/models/tech_skills_campaign.rb
class TechSkillsCampaign < ApplicationRecord
  enum priority: [ :required, :must, :important ]
  enum level: [ :beginner, :intermediate, :professional ]

  belongs_to :tech_skill
  belongs_to :job_campaign

  validates :priority, presence: true
  validates :level, presence: true
end

app/models/tech_skills_student.rb
class TechSkillsStudent < ApplicationRecord
  enum level: [ :beginner, :intermediate, :professional ]

  belongs_to :tech_skill
  belongs_to :student
end

app/models/user.rb
class User < ApplicationRecord
  enum account_type: [ :student, :company, :admin, :super_admin ] #[0, 1, 2, 3]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :student, dependent: :destroy
  has_one :company, dependent: :destroy

  # scope :all_except, -> (user) { admin.where.not(id: user) }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if resource.save
      resource.create_student
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:edit, :destroy]

  def index
    @users = Array.new
    User.all.includes(:student, :company).each do |user|
      @users << user
    end
  end

  def new
    @user = User.all.build
  end

  def edit
  end

  def create
    @user = User.all.build(user_params)
    if user_params['account_type'] == 'student'
      @user.build_student
    elsif user_params['account_type'] == 'company'
      @user.build_company
    end

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
       redirect_to users_path
     else
       render 'edit'
     end
  end

  def destroy
    @user.destroy!    
    redirect_to users_path  
  end

  private
  def get_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :account_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_campaigns_helper.rb
module JobCampaignsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tech_skills_helper.rb
module TechSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container" id="admin-manage-users">
  <div class="row d-flex justify-content-center text-center">
      <h1>ALL USERS</h1>
  </div>
  <!-- <div class="row search">
      <div class="col-2"></div>
      <div class="col-8">
          <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="Search">
              <div class="input-group-append">
                <button class="btn btn-success" type="submit">Go</button>
              </div>
          </div>
      </div>
      <div class="col-2"></div>
  </div> -->
  <div class="row d-flex control_button">
      <div class="col d-flex justify-content-center">
        <!-- <button type="button" class="">All User</button>
          <button type="button" class="">Student</button>
          <button type="button" class="">Company</button>
          <button type="button" class="">Admin</button> -->
          <%= link_to "Add New User", new_user_path, class: "btn btn-secondary pt-2" %>
      </div>
  </div>

  <div class="row table-responsive">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>User #</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>View</th>
            <th>Edit</th>
            <th>Ban</th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= user.id %></td>
            <% if user.student? %>
              <td><%= user.student.name || "" %></td>
            <% elsif user.company? %>
              <td><%= user.company.name || "" %></td>
            <% else %>
              <td></td>
            <% end %>
            <td><%= user.email %></td>
            <td><%= user.account_type %></td>
            <% if user.student? %>
              <td><%= link_to "View", preview_cv_path(user), class: "btn btn-success" %></td>
              <td><%= link_to "Edit", edit_student_path(user), class: "btn btn-success" %></td>
            <% elsif user.company? %>
              <td><%= link_to "View", company_profile_path(user.company), class: "btn btn-success" %></td>
              <td><%= link_to "Edit", edit_company_path(user), class: "btn btn-success" %></td>
            <% else %>
              <td></td>
              <% if current_user.admin? %>
                <% if user.super_admin? || user.admin? %>
                  <td></td>
                <% else %>
                  <td><%= link_to "Edit", edit_user_registration_path, class: "btn btn-success" %></td>
                <% end %>
              <% else %>
                <td><%= link_to "Edit", edit_user_registration_path, class: "btn btn-success" %></td>
              <% end %>
            <% end %>
            <td><a href="#">Ban</a></td>
          </tr>
        </tbody>
        <% end %>
      </table>  
  </div>

  <div class="modal fade" id="myModal">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
        
          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title">Insert User</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          
          <!-- Modal body -->
          <div class="modal-body">
            <div class="container" >
              <div class="row margin_bot_10px">
                  <div class="col-3">Username</div>
                  <div class="col-9"><input type="text" class="width100"></div>
              </div>
              <div class="row margin_bot_10px">
                  <div class="col-3">Password</div>
                  <div class="col-9"><input type="text" class="width100"></div>
              </div>
              <div class="row margin_bot_10px">
                  <div class="col-3">Re-Enter Password</div>
                  <div class="col-9"><input type="text" class="width100"></div>
              </div>
              <div class="row margin_bot_10px">
                  <div class="col-3">Email</div>
                  <div class="col-9"><input type="text" class="width100"></div>
              </div>
              <div class="row margin_bot_10px">
                  <div class="col-3">Role</div>
                  <div class="col-9">
                      <select class="width100" style="height:35px" >
                          <option>User</option>
                          <option>Company</option>
                          <option>Admin</option>
                      </select>                      
                  </div>
              </div>              
            </div>
          </div>
          
          <!-- Modal footer -->
          <div class="modal-footer">
          <button type="button" class="btn btn-primary">Save changes</button>

            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
          
        </div>
      </div>
  </div>
</div>

app/views/users/new.html.erb
<%= simple_form_for @user, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="container" id="admin-manage-new">
  <div class="row d-flex justify-content-center"><h1>Add New</h1></div>
  <div class="row">
      <div class="col-sm-3">Email:</div>
      <div class="col-sm-9">
        <%= f.input :email,
                    required: true,
                    autofocus: true,
                    placeholder: "Enter email",
                    label: false %>
      </div>
  </div>
  <div class="row">
      <div class="col-sm-3">Password:</div>
      <div class="col-sm-9">
        <%= f.input :password,
                    required: true,
                    placeholder: "Enter password",
                    label: false %>
      </div>
  </div>
  <div class="row">
      <div class="col-sm-3">Role:</div>
      <div class="col-sm-9">
        <% if current_user.admin? %>
          <%= f.input :account_type,
                      prompt: 'Student',
                      collection: [
                                    ['Student', 'student'],
                                    ['Company', 'company']
                                  ],
                      label: false %>
        <% else %>
          <%= f.input :account_type,
                      prompt: 'Student',
                      collection: [
                                    ['Student', 'student'],
                                    ['Company', 'company'],
                                    ['Admin', 'admin']
                                  ],
                      label: false %>
        <% end %>
      </div>
  </div>
  <div class="row">
      <div class="col-sm-3"></div>
      <div class="col-sm-9">
        <%= f.button :submit, "Save", class: "btn btn-success w-100" %>
      </div>
  </div>
</div>
<% end %>