config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "students#job_board"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  scope "/admin" do
    resources :languages
    resources :certifications
    resources :category_tech_skills
    resources :tech_skills
    
    resources :users
    resources :students
    resources :companies
  end

  scope "/company" do
    resources :job_campaigns do
      member do
        get 'match_students'
        put 'reject_student/:student_id', to: 'job_campaigns#reject_student', as: :reject_student
      end
    end
    get ':id/edit_profile', to: 'companies#edit', as: 'company_edit_profile'
    get ':id/profile', to: 'companies#view_profile', as: 'company_profile'
  end
  # put 'reject_student/:id', to: 'job_campaigns_students#reject_student'

  scope "/student" do
    get ':id/my_cv', to: 'students#edit', as: 'student_cv'
    get ':id/preview_cv', to: 'students#preview_cv', as: 'preview_cv'
    get 'job_board', to: 'students#job_board', as: 'student_job_board'
    get 'matched_jobs', to: 'job_campaigns#match_job_campaigns', as: 'match_job_campaigns'
  end
  
  get 'admin/job_campaigns', to: 'job_campaigns#admin_manage', as: 'admin_manage_job_campaigns'
  get 'job_campaigns/:id/preview', to: 'job_campaigns#preview_campaign', as: 'preview_campaign'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_tech_skill.rb
class CategoryTechSkill < ApplicationRecord
  has_many :tech_skills
end

app/models/certification.rb
class Certification < ApplicationRecord
  has_many :certifications_users
  has_many :users, through: :certifications_users

  has_many :certifications_campaigns
  has_many :job_campaigns, through: :certifications_campaigns
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_one_attached :logo
  has_one_attached :headline

  has_many :job_campaigns
end

app/models/job_campaign.rb
class JobCampaign < ApplicationRecord
  enum skill_level: [ :internship, :freshman, :professional, :expert ]
  enum is_open: [ :yes, :no ]

  belongs_to :company

  has_many :languages_campaigns, dependent: :destroy
  has_many :languages, through: :languages_campaigns

  has_many :certifications_campaigns, dependent: :destroy
  has_many :certifications, through: :certifications_campaigns

  has_many :tech_skills_campaigns, dependent: :destroy
  has_many :tech_skills, through: :tech_skills_campaigns
  accepts_nested_attributes_for :tech_skills_campaigns, allow_destroy: true

  has_many :job_campaigns_students
  has_many :students, through: :job_campaigns_students

  validates :title, presence: true
  validates :salary, presence: true
  validates :work_hour_per_week, presence: true
  validates :gpa, presence: true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :languages_users
  has_many :users, through: :languages_users

  has_many :languages_campaigns
  has_many :job_campaigns, through: :languages_campaigns
end

app/models/languages_campaign.rb
class LanguagesCampaign < ApplicationRecord
  belongs_to :language
  belongs_to :job_campaign
end

app/models/languages_student.rb
class LanguagesStudent < ApplicationRecord
  belongs_to :language
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  enum is_open: [ :yes, :no ]

  belongs_to :user

  has_one_attached :avatar

  has_many :certifications_students
  has_many :certifications, through: :certifications_students

  has_many :languages_students
  has_many :languages, through: :languages_students

  has_many :tech_skills_students
  has_many :tech_skills, through: :tech_skills_students
  accepts_nested_attributes_for :tech_skills_students, allow_destroy: true

  has_many :job_campaigns_students
  has_many :job_campaigns, through: :job_campaigns_students
end

app/models/tech_skill.rb
class TechSkill < ApplicationRecord
  belongs_to :category_tech_skill, optional: true

  has_many :tech_skills_users
  has_many :users, through: :tech_skills_users

  has_many :tech_skills_campaigns
  has_many :tech_skills, through: :tech_skills_campaigns

  validates :name, presence: true
end

app/models/tech_skills_campaign.rb
class TechSkillsCampaign < ApplicationRecord
  enum priority: [ :required, :must, :important ]
  enum level: [ :beginner, :intermediate, :professional ]

  belongs_to :tech_skill
  belongs_to :job_campaign

  validates :priority, presence: true
  validates :level, presence: true
end

app/models/tech_skills_student.rb
class TechSkillsStudent < ApplicationRecord
  enum level: [ :beginner, :intermediate, :professional ]

  belongs_to :tech_skill
  belongs_to :student
end

app/models/user.rb
class User < ApplicationRecord
  enum account_type: [ :student, :company, :admin, :super_admin ] #[0, 1, 2, 3]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :student, dependent: :destroy
  has_one :company, dependent: :destroy

  # scope :all_except, -> (user) { admin.where.not(id: user) }
end

app/controllers/category_tech_skills_controller.rb
class CategoryTechSkillsController < ApplicationController
  before_action :find_category_tech_skill, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :edit, :destroy]

  def index
    @category_tech_skills = CategoryTechSkill.all
  end

  def show
  end

  def new
    @category_tech_skill = CategoryTechSkill.all.build
  end

  def edit
  end

  def create
    @category_tech_skill = CategoryTechSkill.all.build(category_tech_skill_params)

    if @category_tech_skill.save
      redirect_to category_tech_skills_path
    else
      render :new
    end
  end

  def update
    if @category_tech_skill.update(category_tech_skill_params)
      redirect_to category_tech_skills_path
    else
      render :edit
    end
  end

  def destroy
    @category_tech_skill.destroy
    redirect_to category_tech_skills_path
  end

  private

  def find_category_tech_skill
    @category_tech_skill = CategoryTechSkill.find(params[:id])
  end

  def category_tech_skill_params
    params.require(:category_tech_skill).permit(:name, :description)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_tech_skills_helper.rb
module CategoryTechSkillsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tech_skills_helper.rb
module TechSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/category_tech_skills/edit.html.erb
<%= simple_form_for @category_tech_skill, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="container" id="admin-manage-new-language">
  <div class="row d-flex justify-content-center"><h1>Edit Category Tech Skill</h1></div>
  <div class="row">
      <div class="col-sm-3">Name:</div>
      <div class="col-sm-9">
        <%= f.input :name,
                    required: true,
                    autofocus: true,
                    placeholder: "Enter name",
                    label: false %>
      </div>
  </div>
  <div class="row">
      <div class="col-sm-3">Description:</div>
      <div class="col-sm-9">
        <%= f.input :description,
                    as: :text,
                    required: false,
                    placeholder: "Write some description",
                    label: false %>
      </div>
  </div>
  <div class="row">
      <div class="col-sm-3"></div>
      <div class="col-sm-9">
        <%= f.button :submit, "Save", class: "btn btn-success w-100" %>
      </div>
  </div>
</div>
<% end %>

app/views/category_tech_skills/index.html.erb
<div class="container" id="admin-manage-languages">
  <div class="row d-flex justify-content-center text-center">
      <h1>ALL CATEGORY TECH SKILLS</h1>
  </div>
  <div class="row search">
      <div class="col-2"></div>
      <div class="col-8">
          <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="Search">
              <div class="input-group-append">
                <button class="btn btn-success" type="submit">Go</button>
              </div>
          </div>
      </div>
      <div class="col-2"></div>
  </div>
  <div class="row d-flex control_button">
    <div class="col d-flex justify-content-center">
      <%= link_to "All Tech Skills", tech_skills_path, class: "btn btn-secondary mr-2" %>
      <%= link_to "All Categories", category_tech_skills_path, class: "btn btn-secondary mr-2" %>
      <%= link_to "Add New Tech Skill", new_tech_skill_path, class: "btn btn-secondary mr-2" %>
      <%= link_to "Add New Category", new_category_tech_skill_path, class: "btn btn-secondary" %>
    </div>
  </div>
  <div class="row table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Cate #</th>
          <th>Name</th>
          <th>Description</th>
          <th>Action</th>
        </tr>
      </thead>
      <% @category_tech_skills.each do |cate| %>
      <tbody>
        <tr>
          <td><%= cate.id %></td>
          <td><%= cate.name %></td>
          <td class="text-truncate" style="max-width: 200px"><%= cate.description %></td>
          <td>
            <%= link_to "Edit", edit_category_tech_skill_path(cate), class: "btn btn-primary mr-1" %>
            <%= link_to "Delete", category_tech_skill_path(cate), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </td>
        </tr>      
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/category_tech_skills/new.html.erb
<%= simple_form_for @category_tech_skill, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<div class="container" id="admin-manage-new">
  <div class="row d-flex justify-content-center"><h1>Add New</h1></div>
  <div class="row">
      <div class="col-sm-3">Name:</div>
      <div class="col-sm-9">
        <%= f.input :name,
                    required: true,
                    autofocus: true,
                    placeholder: "Enter name",
                    label: false %>
      </div>
  </div>
  <div class="row">
      <div class="col-sm-3">Description:</div>
      <div class="col-sm-9">
        <%= f.input :description,
                    as: :text,
                    required: false,
                    placeholder: "Write some description",
                    label: false %>
      </div>
  </div>
  <div class="row">
      <div class="col-sm-3"></div>
      <div class="col-sm-9">
        <%= f.button :submit, "Save", class: "btn btn-success w-100" %>
      </div>
  </div>
</div>
<% end %>