config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "students#job_board"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  scope "/admin" do
    resources :languages
    resources :certifications
    resources :category_tech_skills
    resources :tech_skills
    
    resources :users
    resources :students
    resources :companies
  end

  scope "/company" do
    resources :job_campaigns do
      member do
        get 'match_students'
        put 'reject_student/:student_id', to: 'job_campaigns#reject_student', as: :reject_student
      end
    end
    get ':id/edit_profile', to: 'companies#edit', as: 'company_edit_profile'
    get ':id/profile', to: 'companies#view_profile', as: 'company_profile'
  end
  # put 'reject_student/:id', to: 'job_campaigns_students#reject_student'

  scope "/student" do
    get ':id/my_cv', to: 'students#edit', as: 'student_cv'
    get ':id/preview_cv', to: 'students#preview_cv', as: 'preview_cv'
    get 'job_board', to: 'students#job_board', as: 'student_job_board'
    get 'matched_jobs', to: 'job_campaigns#match_job_campaigns', as: 'match_job_campaigns'
  end
  
  get 'admin/job_campaigns', to: 'job_campaigns#admin_manage', as: 'admin_manage_job_campaigns'
  get 'job_campaigns/:id/preview', to: 'job_campaigns#preview_campaign', as: 'preview_campaign'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_tech_skill.rb
class CategoryTechSkill < ApplicationRecord
  has_many :tech_skills
end

app/models/certification.rb
class Certification < ApplicationRecord
  has_many :certifications_users
  has_many :users, through: :certifications_users

  has_many :certifications_campaigns
  has_many :job_campaigns, through: :certifications_campaigns
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_one_attached :logo
  has_one_attached :headline

  has_many :job_campaigns
end

app/models/job_campaign.rb
class JobCampaign < ApplicationRecord
  enum skill_level: [ :internship, :freshman, :professional, :expert ]
  enum is_open: [ :yes, :no ]

  belongs_to :company

  has_many :languages_campaigns, dependent: :destroy
  has_many :languages, through: :languages_campaigns

  has_many :certifications_campaigns, dependent: :destroy
  has_many :certifications, through: :certifications_campaigns

  has_many :tech_skills_campaigns, dependent: :destroy
  has_many :tech_skills, through: :tech_skills_campaigns
  accepts_nested_attributes_for :tech_skills_campaigns, allow_destroy: true

  has_many :job_campaigns_students
  has_many :students, through: :job_campaigns_students

  validates :title, presence: true
  validates :salary, presence: true
  validates :work_hour_per_week, presence: true
  validates :gpa, presence: true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :languages_users
  has_many :users, through: :languages_users

  has_many :languages_campaigns
  has_many :job_campaigns, through: :languages_campaigns
end

app/models/languages_campaign.rb
class LanguagesCampaign < ApplicationRecord
  belongs_to :language
  belongs_to :job_campaign
end

app/models/languages_student.rb
class LanguagesStudent < ApplicationRecord
  belongs_to :language
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  enum is_open: [ :yes, :no ]

  belongs_to :user

  has_one_attached :avatar

  has_many :certifications_students
  has_many :certifications, through: :certifications_students

  has_many :languages_students
  has_many :languages, through: :languages_students

  has_many :tech_skills_students
  has_many :tech_skills, through: :tech_skills_students
  accepts_nested_attributes_for :tech_skills_students, allow_destroy: true

  has_many :job_campaigns_students
  has_many :job_campaigns, through: :job_campaigns_students
end

app/models/tech_skill.rb
class TechSkill < ApplicationRecord
  belongs_to :category_tech_skill, optional: true

  has_many :tech_skills_users
  has_many :users, through: :tech_skills_users

  has_many :tech_skills_campaigns
  has_many :tech_skills, through: :tech_skills_campaigns

  validates :name, presence: true
end

app/models/tech_skills_student.rb
class TechSkillsStudent < ApplicationRecord
  enum level: [ :beginner, :intermediate, :professional ]

  belongs_to :tech_skill
  belongs_to :student
end

app/models/user.rb
class User < ApplicationRecord
  enum account_type: [ :student, :company, :admin, :super_admin ] #[0, 1, 2, 3]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :student, dependent: :destroy
  has_one :company, dependent: :destroy

  # scope :all_except, -> (user) { admin.where.not(id: user) }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tech_skills_helper.rb
module TechSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <% if current_user.student? %>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:beige !important;">
    <%= link_to 'Student Board', student_job_board_path, class: "navbar-brand logo_font font-weight-bold" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">  
        <li class="nav-item dropdown">
          <%= link_to 'Profile', preview_cv_path(current_user), class: "text-decoration-none font-weight-bold text-secondary ml-2 mr-4" %>
        </li>
        <li class="nav-item">
          <%= link_to 'View Matched Companies', match_job_campaigns_path, class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
        </li>    
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <% if current_user.student? %>
            <li class="nav-item">
              <%= link_to 'My CV', student_cv_path(current_user), class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
            </li>
          <% elsif current_user.company? %>
            <li class="nav-item">
              <%= link_to 'Edit Profile', company_edit_profile_path(current_user), class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to edit_user_registration_path, class: "text-decoration-none font-weight-bold text-secondary mr-4" do %>
              <%= current_user.email %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary mr-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>      
  </nav>
  <% elsif current_user.company? %>
  <nav class="navbar navbar-expand-md navbar-light bg-light py-3">
    <%= link_to "Company Profile", company_profile_path(current_user.company), class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Campaigns", job_campaigns_path, class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <% if current_user.student? %>
            <li class="nav-item">
              <%= link_to 'My CV', student_cv_path(current_user), class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
            </li>
          <% elsif current_user.company? %>
            <li class="nav-item">
              <%= link_to 'Edit Profile', company_edit_profile_path(current_user), class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to edit_user_registration_path, class: "text-decoration-none font-weight-bold text-secondary mr-4" do %>
              <%= current_user.email %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary mr-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <% elsif current_user.admin? || current_user.super_admin? %>
  <nav class="navbar navbar-expand-lg navbar-light py-3" style="background-color: beige !important">
    <%= link_to "Admin Board", users_path, class: "text-decoration-none font-weight-bold text-secondary" %>
    <%= link_to "Languages", languages_path, class: "text-decoration-none font-weight-bold text-secondary ml-4" %>
    <%= link_to "Certifications", certifications_path, class: "text-decoration-none font-weight-bold text-secondary ml-4" %>
    <%= link_to "Tech Skills", tech_skills_path, class: "text-decoration-none font-weight-bold text-secondary ml-4" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <% if current_user.student? %>
            <li class="nav-item">
              <%= link_to 'My CV', student_cv_path(current_user), class: "btn btn-primary mr-2" %>
            </li>
          <% elsif current_user.company? %>
            <li class="nav-item">
              <%= link_to 'Edit Profile', company_edit_profile_path(current_user), class: "btn btn-primary mr-2" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to edit_user_registration_path, class: "text-decoration-none font-weight-bold text-secondary mr-4" do %>
              <%= current_user.email %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary mr-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <% end %>
<% else %>
<nav class="navbar navbar-expand-lg navbar-light py-3" style="background-color: beige !important">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= link_to "Job Matching", root_path, class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "text-decoration-none font-weight-bold text-secondary mr-4" %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobMatchingBe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>